/* tslint:disable */
/* eslint-disable */
//  This file was automatically generated and should not be edited.

export type CreateClientInput = {
  id?: string | null,
  clientId: string,
  clientTypeId: string,
  firstName: string,
  lastName: string,
  companyName?: string | null,
  account: string,
  receiveMailInd: boolean,
  nextItemNumber: string,
  phone?: string | null,
  email?: string | null,
  createTimestamp?: string | null,
  activeTimestamp?: string | null,
  inactiveTimestamp?: string | null,
  modifiedBy: string,
  _version?: number | null,
};

export type ModelClientConditionInput = {
  clientId?: ModelStringInput | null,
  clientTypeId?: ModelStringInput | null,
  firstName?: ModelStringInput | null,
  lastName?: ModelStringInput | null,
  companyName?: ModelStringInput | null,
  account?: ModelStringInput | null,
  receiveMailInd?: ModelBooleanInput | null,
  nextItemNumber?: ModelStringInput | null,
  phone?: ModelStringInput | null,
  email?: ModelStringInput | null,
  createTimestamp?: ModelStringInput | null,
  activeTimestamp?: ModelStringInput | null,
  inactiveTimestamp?: ModelStringInput | null,
  modifiedBy?: ModelStringInput | null,
  and?: Array< ModelClientConditionInput | null > | null,
  or?: Array< ModelClientConditionInput | null > | null,
  not?: ModelClientConditionInput | null,
};

export type ModelStringInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  size?: ModelSizeInput | null,
};

export enum ModelAttributeTypes {
  binary = "binary",
  binarySet = "binarySet",
  bool = "bool",
  list = "list",
  map = "map",
  number = "number",
  numberSet = "numberSet",
  string = "string",
  stringSet = "stringSet",
  _null = "_null",
}


export type ModelSizeInput = {
  ne?: number | null,
  eq?: number | null,
  le?: number | null,
  lt?: number | null,
  ge?: number | null,
  gt?: number | null,
  between?: Array< number | null > | null,
};

export type ModelBooleanInput = {
  ne?: boolean | null,
  eq?: boolean | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
};

export type Client = {
  __typename: "Client",
  id: string,
  clientId: string,
  clientTypeId: string,
  firstName: string,
  lastName: string,
  companyName?: string | null,
  account: string,
  receiveMailInd: boolean,
  nextItemNumber: string,
  phone?: string | null,
  email?: string | null,
  createTimestamp?: string | null,
  activeTimestamp?: string | null,
  inactiveTimestamp?: string | null,
  modifiedBy: string,
  items?:  Array<Item | null > | null,
  createdAt: string,
  updatedAt: string,
  _version: number,
  _deleted?: boolean | null,
  _lastChangedAt: number,
};

export type Item = {
  __typename: "Item",
  itemId: string,
  priceCodeId: string,
  userId: string,
  commissionId: string,
  itemAcquireTypeId: string,
  categoryId: string,
  locationId: string,
  sectionId: string,
  statusId: string,
  taxTypeId: string,
  number: string,
  name: string,
  description: string,
  price: string,
  cost: string,
  modifiedBy: string,
  consignmentId: string,
  id: string,
  createdAt: string,
  updatedAt: string,
  _version: number,
  _deleted?: boolean | null,
  _lastChangedAt: number,
};

export type UpdateClientInput = {
  id: string,
  clientId?: string | null,
  clientTypeId?: string | null,
  firstName?: string | null,
  lastName?: string | null,
  companyName?: string | null,
  account?: string | null,
  receiveMailInd?: boolean | null,
  nextItemNumber?: string | null,
  phone?: string | null,
  email?: string | null,
  createTimestamp?: string | null,
  activeTimestamp?: string | null,
  inactiveTimestamp?: string | null,
  modifiedBy?: string | null,
  _version?: number | null,
};

export type DeleteClientInput = {
  id: string,
  _version?: number | null,
};

export type CreateItemInput = {
  itemId: string,
  priceCodeId: string,
  userId: string,
  commissionId: string,
  itemAcquireTypeId: string,
  categoryId: string,
  locationId: string,
  sectionId: string,
  statusId: string,
  taxTypeId: string,
  number: string,
  name: string,
  description: string,
  price: string,
  cost: string,
  modifiedBy: string,
  consignmentId: string,
  id?: string | null,
  _version?: number | null,
};

export type ModelItemConditionInput = {
  itemId?: ModelStringInput | null,
  priceCodeId?: ModelStringInput | null,
  userId?: ModelStringInput | null,
  commissionId?: ModelStringInput | null,
  itemAcquireTypeId?: ModelStringInput | null,
  categoryId?: ModelStringInput | null,
  locationId?: ModelStringInput | null,
  sectionId?: ModelStringInput | null,
  statusId?: ModelStringInput | null,
  taxTypeId?: ModelStringInput | null,
  number?: ModelStringInput | null,
  name?: ModelStringInput | null,
  description?: ModelStringInput | null,
  price?: ModelStringInput | null,
  cost?: ModelStringInput | null,
  modifiedBy?: ModelStringInput | null,
  consignmentId?: ModelStringInput | null,
  and?: Array< ModelItemConditionInput | null > | null,
  or?: Array< ModelItemConditionInput | null > | null,
  not?: ModelItemConditionInput | null,
};

export type UpdateItemInput = {
  itemId?: string | null,
  priceCodeId?: string | null,
  userId?: string | null,
  commissionId?: string | null,
  itemAcquireTypeId?: string | null,
  categoryId?: string | null,
  locationId?: string | null,
  sectionId?: string | null,
  statusId?: string | null,
  taxTypeId?: string | null,
  number?: string | null,
  name?: string | null,
  description?: string | null,
  price?: string | null,
  cost?: string | null,
  modifiedBy?: string | null,
  consignmentId?: string | null,
  id: string,
  _version?: number | null,
};

export type DeleteItemInput = {
  id: string,
  _version?: number | null,
};

export type SearchableClientFilterInput = {
  id?: SearchableIDFilterInput | null,
  clientId?: SearchableStringFilterInput | null,
  clientTypeId?: SearchableStringFilterInput | null,
  firstName?: SearchableStringFilterInput | null,
  lastName?: SearchableStringFilterInput | null,
  companyName?: SearchableStringFilterInput | null,
  account?: SearchableStringFilterInput | null,
  receiveMailInd?: SearchableBooleanFilterInput | null,
  nextItemNumber?: SearchableStringFilterInput | null,
  phone?: SearchableStringFilterInput | null,
  email?: SearchableStringFilterInput | null,
  createTimestamp?: SearchableStringFilterInput | null,
  activeTimestamp?: SearchableStringFilterInput | null,
  inactiveTimestamp?: SearchableStringFilterInput | null,
  modifiedBy?: SearchableStringFilterInput | null,
  createdAt?: SearchableStringFilterInput | null,
  updatedAt?: SearchableStringFilterInput | null,
  _version?: SearchableIntFilterInput | null,
  _deleted?: SearchableBooleanFilterInput | null,
  _lastChangedAt?: SearchableIntFilterInput | null,
  and?: Array< SearchableClientFilterInput | null > | null,
  or?: Array< SearchableClientFilterInput | null > | null,
  not?: SearchableClientFilterInput | null,
};

export type SearchableIDFilterInput = {
  ne?: string | null,
  gt?: string | null,
  lt?: string | null,
  gte?: string | null,
  lte?: string | null,
  eq?: string | null,
  match?: string | null,
  matchPhrase?: string | null,
  matchPhrasePrefix?: string | null,
  multiMatch?: string | null,
  exists?: boolean | null,
  wildcard?: string | null,
  regexp?: string | null,
  range?: Array< string | null > | null,
};

export type SearchableStringFilterInput = {
  ne?: string | null,
  gt?: string | null,
  lt?: string | null,
  gte?: string | null,
  lte?: string | null,
  eq?: string | null,
  match?: string | null,
  matchPhrase?: string | null,
  matchPhrasePrefix?: string | null,
  multiMatch?: string | null,
  exists?: boolean | null,
  wildcard?: string | null,
  regexp?: string | null,
  range?: Array< string | null > | null,
};

export type SearchableBooleanFilterInput = {
  eq?: boolean | null,
  ne?: boolean | null,
};

export type SearchableIntFilterInput = {
  ne?: number | null,
  gt?: number | null,
  lt?: number | null,
  gte?: number | null,
  lte?: number | null,
  eq?: number | null,
  range?: Array< number | null > | null,
};

export type SearchableClientSortInput = {
  field?: SearchableClientSortableFields | null,
  direction?: SearchableSortDirection | null,
};

export enum SearchableClientSortableFields {
  id = "id",
  clientId = "clientId",
  clientTypeId = "clientTypeId",
  firstName = "firstName",
  lastName = "lastName",
  companyName = "companyName",
  account = "account",
  receiveMailInd = "receiveMailInd",
  nextItemNumber = "nextItemNumber",
  phone = "phone",
  email = "email",
  createTimestamp = "createTimestamp",
  activeTimestamp = "activeTimestamp",
  inactiveTimestamp = "inactiveTimestamp",
  modifiedBy = "modifiedBy",
  createdAt = "createdAt",
  updatedAt = "updatedAt",
  _version = "_version",
  _deleted = "_deleted",
  _lastChangedAt = "_lastChangedAt",
}


export enum SearchableSortDirection {
  asc = "asc",
  desc = "desc",
}


export type SearchableClientAggregationInput = {
  name: string,
  type: SearchableAggregateType,
  field: SearchableClientAggregateField,
};

export enum SearchableAggregateType {
  terms = "terms",
  avg = "avg",
  min = "min",
  max = "max",
  sum = "sum",
}


export enum SearchableClientAggregateField {
  id = "id",
  clientId = "clientId",
  clientTypeId = "clientTypeId",
  firstName = "firstName",
  lastName = "lastName",
  companyName = "companyName",
  account = "account",
  receiveMailInd = "receiveMailInd",
  nextItemNumber = "nextItemNumber",
  phone = "phone",
  email = "email",
  createTimestamp = "createTimestamp",
  activeTimestamp = "activeTimestamp",
  inactiveTimestamp = "inactiveTimestamp",
  modifiedBy = "modifiedBy",
  createdAt = "createdAt",
  updatedAt = "updatedAt",
  _version = "_version",
  _deleted = "_deleted",
  _lastChangedAt = "_lastChangedAt",
}


export type SearchableClientConnection = {
  __typename: "SearchableClientConnection",
  items:  Array<Client | null >,
  nextToken?: string | null,
  total?: number | null,
  aggregateItems:  Array<SearchableAggregateResult | null >,
};

export type SearchableAggregateResult = {
  __typename: "SearchableAggregateResult",
  name: string,
  result?: SearchableAggregateGenericResult | null,
};

export type SearchableAggregateGenericResult = SearchableAggregateScalarResult | SearchableAggregateBucketResult


export type SearchableAggregateScalarResult = {
  __typename: "SearchableAggregateScalarResult",
  value: number,
};

export type SearchableAggregateBucketResult = {
  __typename: "SearchableAggregateBucketResult",
  buckets?:  Array<SearchableAggregateBucketResultItem | null > | null,
};

export type SearchableAggregateBucketResultItem = {
  __typename: "SearchableAggregateBucketResultItem",
  key: string,
  doc_count: number,
};

export type ModelClientFilterInput = {
  id?: ModelIDInput | null,
  clientId?: ModelStringInput | null,
  clientTypeId?: ModelStringInput | null,
  firstName?: ModelStringInput | null,
  lastName?: ModelStringInput | null,
  companyName?: ModelStringInput | null,
  account?: ModelStringInput | null,
  receiveMailInd?: ModelBooleanInput | null,
  nextItemNumber?: ModelStringInput | null,
  phone?: ModelStringInput | null,
  email?: ModelStringInput | null,
  createTimestamp?: ModelStringInput | null,
  activeTimestamp?: ModelStringInput | null,
  inactiveTimestamp?: ModelStringInput | null,
  modifiedBy?: ModelStringInput | null,
  and?: Array< ModelClientFilterInput | null > | null,
  or?: Array< ModelClientFilterInput | null > | null,
  not?: ModelClientFilterInput | null,
};

export type ModelIDInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  size?: ModelSizeInput | null,
};

export type ModelClientConnection = {
  __typename: "ModelClientConnection",
  items:  Array<Client | null >,
  nextToken?: string | null,
  startedAt?: number | null,
};

export type ModelItemFilterInput = {
  itemId?: ModelStringInput | null,
  priceCodeId?: ModelStringInput | null,
  userId?: ModelStringInput | null,
  commissionId?: ModelStringInput | null,
  itemAcquireTypeId?: ModelStringInput | null,
  categoryId?: ModelStringInput | null,
  locationId?: ModelStringInput | null,
  sectionId?: ModelStringInput | null,
  statusId?: ModelStringInput | null,
  taxTypeId?: ModelStringInput | null,
  number?: ModelStringInput | null,
  name?: ModelStringInput | null,
  description?: ModelStringInput | null,
  price?: ModelStringInput | null,
  cost?: ModelStringInput | null,
  modifiedBy?: ModelStringInput | null,
  consignmentId?: ModelStringInput | null,
  and?: Array< ModelItemFilterInput | null > | null,
  or?: Array< ModelItemFilterInput | null > | null,
  not?: ModelItemFilterInput | null,
};

export type ModelItemConnection = {
  __typename: "ModelItemConnection",
  items:  Array<Item | null >,
  nextToken?: string | null,
  startedAt?: number | null,
};

export type ModelSubscriptionClientFilterInput = {
  id?: ModelSubscriptionIDInput | null,
  clientId?: ModelSubscriptionStringInput | null,
  clientTypeId?: ModelSubscriptionStringInput | null,
  firstName?: ModelSubscriptionStringInput | null,
  lastName?: ModelSubscriptionStringInput | null,
  companyName?: ModelSubscriptionStringInput | null,
  account?: ModelSubscriptionStringInput | null,
  receiveMailInd?: ModelSubscriptionBooleanInput | null,
  nextItemNumber?: ModelSubscriptionStringInput | null,
  phone?: ModelSubscriptionStringInput | null,
  email?: ModelSubscriptionStringInput | null,
  createTimestamp?: ModelSubscriptionStringInput | null,
  activeTimestamp?: ModelSubscriptionStringInput | null,
  inactiveTimestamp?: ModelSubscriptionStringInput | null,
  modifiedBy?: ModelSubscriptionStringInput | null,
  and?: Array< ModelSubscriptionClientFilterInput | null > | null,
  or?: Array< ModelSubscriptionClientFilterInput | null > | null,
};

export type ModelSubscriptionIDInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  in?: Array< string | null > | null,
  notIn?: Array< string | null > | null,
};

export type ModelSubscriptionStringInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  in?: Array< string | null > | null,
  notIn?: Array< string | null > | null,
};

export type ModelSubscriptionBooleanInput = {
  ne?: boolean | null,
  eq?: boolean | null,
};

export type ModelSubscriptionItemFilterInput = {
  itemId?: ModelSubscriptionStringInput | null,
  priceCodeId?: ModelSubscriptionStringInput | null,
  userId?: ModelSubscriptionStringInput | null,
  commissionId?: ModelSubscriptionStringInput | null,
  itemAcquireTypeId?: ModelSubscriptionStringInput | null,
  categoryId?: ModelSubscriptionStringInput | null,
  locationId?: ModelSubscriptionStringInput | null,
  sectionId?: ModelSubscriptionStringInput | null,
  statusId?: ModelSubscriptionStringInput | null,
  taxTypeId?: ModelSubscriptionStringInput | null,
  number?: ModelSubscriptionStringInput | null,
  name?: ModelSubscriptionStringInput | null,
  description?: ModelSubscriptionStringInput | null,
  price?: ModelSubscriptionStringInput | null,
  cost?: ModelSubscriptionStringInput | null,
  modifiedBy?: ModelSubscriptionStringInput | null,
  consignmentId?: ModelSubscriptionStringInput | null,
  and?: Array< ModelSubscriptionItemFilterInput | null > | null,
  or?: Array< ModelSubscriptionItemFilterInput | null > | null,
};

export type CreateClientMutationVariables = {
  input: CreateClientInput,
  condition?: ModelClientConditionInput | null,
};

export type CreateClientMutation = {
  createClient?:  {
    __typename: "Client",
    id: string,
    clientId: string,
    clientTypeId: string,
    firstName: string,
    lastName: string,
    companyName?: string | null,
    account: string,
    receiveMailInd: boolean,
    nextItemNumber: string,
    phone?: string | null,
    email?: string | null,
    createTimestamp?: string | null,
    activeTimestamp?: string | null,
    inactiveTimestamp?: string | null,
    modifiedBy: string,
    items?:  Array< {
      __typename: "Item",
      itemId: string,
      priceCodeId: string,
      userId: string,
      commissionId: string,
      itemAcquireTypeId: string,
      categoryId: string,
      locationId: string,
      sectionId: string,
      statusId: string,
      taxTypeId: string,
      number: string,
      name: string,
      description: string,
      price: string,
      cost: string,
      modifiedBy: string,
      consignmentId: string,
      id: string,
      createdAt: string,
      updatedAt: string,
      _version: number,
      _deleted?: boolean | null,
      _lastChangedAt: number,
    } | null > | null,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
  } | null,
};

export type UpdateClientMutationVariables = {
  input: UpdateClientInput,
  condition?: ModelClientConditionInput | null,
};

export type UpdateClientMutation = {
  updateClient?:  {
    __typename: "Client",
    id: string,
    clientId: string,
    clientTypeId: string,
    firstName: string,
    lastName: string,
    companyName?: string | null,
    account: string,
    receiveMailInd: boolean,
    nextItemNumber: string,
    phone?: string | null,
    email?: string | null,
    createTimestamp?: string | null,
    activeTimestamp?: string | null,
    inactiveTimestamp?: string | null,
    modifiedBy: string,
    items?:  Array< {
      __typename: "Item",
      itemId: string,
      priceCodeId: string,
      userId: string,
      commissionId: string,
      itemAcquireTypeId: string,
      categoryId: string,
      locationId: string,
      sectionId: string,
      statusId: string,
      taxTypeId: string,
      number: string,
      name: string,
      description: string,
      price: string,
      cost: string,
      modifiedBy: string,
      consignmentId: string,
      id: string,
      createdAt: string,
      updatedAt: string,
      _version: number,
      _deleted?: boolean | null,
      _lastChangedAt: number,
    } | null > | null,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
  } | null,
};

export type DeleteClientMutationVariables = {
  input: DeleteClientInput,
  condition?: ModelClientConditionInput | null,
};

export type DeleteClientMutation = {
  deleteClient?:  {
    __typename: "Client",
    id: string,
    clientId: string,
    clientTypeId: string,
    firstName: string,
    lastName: string,
    companyName?: string | null,
    account: string,
    receiveMailInd: boolean,
    nextItemNumber: string,
    phone?: string | null,
    email?: string | null,
    createTimestamp?: string | null,
    activeTimestamp?: string | null,
    inactiveTimestamp?: string | null,
    modifiedBy: string,
    items?:  Array< {
      __typename: "Item",
      itemId: string,
      priceCodeId: string,
      userId: string,
      commissionId: string,
      itemAcquireTypeId: string,
      categoryId: string,
      locationId: string,
      sectionId: string,
      statusId: string,
      taxTypeId: string,
      number: string,
      name: string,
      description: string,
      price: string,
      cost: string,
      modifiedBy: string,
      consignmentId: string,
      id: string,
      createdAt: string,
      updatedAt: string,
      _version: number,
      _deleted?: boolean | null,
      _lastChangedAt: number,
    } | null > | null,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
  } | null,
};

export type CreateItemMutationVariables = {
  input: CreateItemInput,
  condition?: ModelItemConditionInput | null,
};

export type CreateItemMutation = {
  createItem?:  {
    __typename: "Item",
    itemId: string,
    priceCodeId: string,
    userId: string,
    commissionId: string,
    itemAcquireTypeId: string,
    categoryId: string,
    locationId: string,
    sectionId: string,
    statusId: string,
    taxTypeId: string,
    number: string,
    name: string,
    description: string,
    price: string,
    cost: string,
    modifiedBy: string,
    consignmentId: string,
    id: string,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
  } | null,
};

export type UpdateItemMutationVariables = {
  input: UpdateItemInput,
  condition?: ModelItemConditionInput | null,
};

export type UpdateItemMutation = {
  updateItem?:  {
    __typename: "Item",
    itemId: string,
    priceCodeId: string,
    userId: string,
    commissionId: string,
    itemAcquireTypeId: string,
    categoryId: string,
    locationId: string,
    sectionId: string,
    statusId: string,
    taxTypeId: string,
    number: string,
    name: string,
    description: string,
    price: string,
    cost: string,
    modifiedBy: string,
    consignmentId: string,
    id: string,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
  } | null,
};

export type DeleteItemMutationVariables = {
  input: DeleteItemInput,
  condition?: ModelItemConditionInput | null,
};

export type DeleteItemMutation = {
  deleteItem?:  {
    __typename: "Item",
    itemId: string,
    priceCodeId: string,
    userId: string,
    commissionId: string,
    itemAcquireTypeId: string,
    categoryId: string,
    locationId: string,
    sectionId: string,
    statusId: string,
    taxTypeId: string,
    number: string,
    name: string,
    description: string,
    price: string,
    cost: string,
    modifiedBy: string,
    consignmentId: string,
    id: string,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
  } | null,
};

export type SearchClientsQueryVariables = {
  filter?: SearchableClientFilterInput | null,
  sort?: Array< SearchableClientSortInput | null > | null,
  limit?: number | null,
  nextToken?: string | null,
  from?: number | null,
  aggregates?: Array< SearchableClientAggregationInput | null > | null,
};

export type SearchClientsQuery = {
  searchClients?:  {
    __typename: "SearchableClientConnection",
    items:  Array< {
      __typename: "Client",
      id: string,
      clientId: string,
      clientTypeId: string,
      firstName: string,
      lastName: string,
      companyName?: string | null,
      account: string,
      receiveMailInd: boolean,
      nextItemNumber: string,
      phone?: string | null,
      email?: string | null,
      createTimestamp?: string | null,
      activeTimestamp?: string | null,
      inactiveTimestamp?: string | null,
      modifiedBy: string,
      items?:  Array< {
        __typename: "Item",
        itemId: string,
        priceCodeId: string,
        userId: string,
        commissionId: string,
        itemAcquireTypeId: string,
        categoryId: string,
        locationId: string,
        sectionId: string,
        statusId: string,
        taxTypeId: string,
        number: string,
        name: string,
        description: string,
        price: string,
        cost: string,
        modifiedBy: string,
        consignmentId: string,
        id: string,
        createdAt: string,
        updatedAt: string,
        _version: number,
        _deleted?: boolean | null,
        _lastChangedAt: number,
      } | null > | null,
      createdAt: string,
      updatedAt: string,
      _version: number,
      _deleted?: boolean | null,
      _lastChangedAt: number,
    } | null >,
    nextToken?: string | null,
    total?: number | null,
    aggregateItems:  Array< {
      __typename: "SearchableAggregateResult",
      name: string,
      result: ( {
          __typename: "SearchableAggregateScalarResult",
          value: number,
        } | {
          __typename: "SearchableAggregateBucketResult",
          buckets?:  Array< {
            __typename: string,
            key: string,
            doc_count: number,
          } | null > | null,
        }
      ) | null,
    } | null >,
  } | null,
};

export type GetClientQueryVariables = {
  id: string,
};

export type GetClientQuery = {
  getClient?:  {
    __typename: "Client",
    id: string,
    clientId: string,
    clientTypeId: string,
    firstName: string,
    lastName: string,
    companyName?: string | null,
    account: string,
    receiveMailInd: boolean,
    nextItemNumber: string,
    phone?: string | null,
    email?: string | null,
    createTimestamp?: string | null,
    activeTimestamp?: string | null,
    inactiveTimestamp?: string | null,
    modifiedBy: string,
    items?:  Array< {
      __typename: "Item",
      itemId: string,
      priceCodeId: string,
      userId: string,
      commissionId: string,
      itemAcquireTypeId: string,
      categoryId: string,
      locationId: string,
      sectionId: string,
      statusId: string,
      taxTypeId: string,
      number: string,
      name: string,
      description: string,
      price: string,
      cost: string,
      modifiedBy: string,
      consignmentId: string,
      id: string,
      createdAt: string,
      updatedAt: string,
      _version: number,
      _deleted?: boolean | null,
      _lastChangedAt: number,
    } | null > | null,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
  } | null,
};

export type ListClientsQueryVariables = {
  filter?: ModelClientFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListClientsQuery = {
  listClients?:  {
    __typename: "ModelClientConnection",
    items:  Array< {
      __typename: "Client",
      id: string,
      clientId: string,
      clientTypeId: string,
      firstName: string,
      lastName: string,
      companyName?: string | null,
      account: string,
      receiveMailInd: boolean,
      nextItemNumber: string,
      phone?: string | null,
      email?: string | null,
      createTimestamp?: string | null,
      activeTimestamp?: string | null,
      inactiveTimestamp?: string | null,
      modifiedBy: string,
      items?:  Array< {
        __typename: "Item",
        itemId: string,
        priceCodeId: string,
        userId: string,
        commissionId: string,
        itemAcquireTypeId: string,
        categoryId: string,
        locationId: string,
        sectionId: string,
        statusId: string,
        taxTypeId: string,
        number: string,
        name: string,
        description: string,
        price: string,
        cost: string,
        modifiedBy: string,
        consignmentId: string,
        id: string,
        createdAt: string,
        updatedAt: string,
        _version: number,
        _deleted?: boolean | null,
        _lastChangedAt: number,
      } | null > | null,
      createdAt: string,
      updatedAt: string,
      _version: number,
      _deleted?: boolean | null,
      _lastChangedAt: number,
    } | null >,
    nextToken?: string | null,
    startedAt?: number | null,
  } | null,
};

export type SyncClientsQueryVariables = {
  filter?: ModelClientFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
  lastSync?: number | null,
};

export type SyncClientsQuery = {
  syncClients?:  {
    __typename: "ModelClientConnection",
    items:  Array< {
      __typename: "Client",
      id: string,
      clientId: string,
      clientTypeId: string,
      firstName: string,
      lastName: string,
      companyName?: string | null,
      account: string,
      receiveMailInd: boolean,
      nextItemNumber: string,
      phone?: string | null,
      email?: string | null,
      createTimestamp?: string | null,
      activeTimestamp?: string | null,
      inactiveTimestamp?: string | null,
      modifiedBy: string,
      items?:  Array< {
        __typename: "Item",
        itemId: string,
        priceCodeId: string,
        userId: string,
        commissionId: string,
        itemAcquireTypeId: string,
        categoryId: string,
        locationId: string,
        sectionId: string,
        statusId: string,
        taxTypeId: string,
        number: string,
        name: string,
        description: string,
        price: string,
        cost: string,
        modifiedBy: string,
        consignmentId: string,
        id: string,
        createdAt: string,
        updatedAt: string,
        _version: number,
        _deleted?: boolean | null,
        _lastChangedAt: number,
      } | null > | null,
      createdAt: string,
      updatedAt: string,
      _version: number,
      _deleted?: boolean | null,
      _lastChangedAt: number,
    } | null >,
    nextToken?: string | null,
    startedAt?: number | null,
  } | null,
};

export type GetItemQueryVariables = {
  id: string,
};

export type GetItemQuery = {
  getItem?:  {
    __typename: "Item",
    itemId: string,
    priceCodeId: string,
    userId: string,
    commissionId: string,
    itemAcquireTypeId: string,
    categoryId: string,
    locationId: string,
    sectionId: string,
    statusId: string,
    taxTypeId: string,
    number: string,
    name: string,
    description: string,
    price: string,
    cost: string,
    modifiedBy: string,
    consignmentId: string,
    id: string,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
  } | null,
};

export type ListItemsQueryVariables = {
  filter?: ModelItemFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListItemsQuery = {
  listItems?:  {
    __typename: "ModelItemConnection",
    items:  Array< {
      __typename: "Item",
      itemId: string,
      priceCodeId: string,
      userId: string,
      commissionId: string,
      itemAcquireTypeId: string,
      categoryId: string,
      locationId: string,
      sectionId: string,
      statusId: string,
      taxTypeId: string,
      number: string,
      name: string,
      description: string,
      price: string,
      cost: string,
      modifiedBy: string,
      consignmentId: string,
      id: string,
      createdAt: string,
      updatedAt: string,
      _version: number,
      _deleted?: boolean | null,
      _lastChangedAt: number,
    } | null >,
    nextToken?: string | null,
    startedAt?: number | null,
  } | null,
};

export type SyncItemsQueryVariables = {
  filter?: ModelItemFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
  lastSync?: number | null,
};

export type SyncItemsQuery = {
  syncItems?:  {
    __typename: "ModelItemConnection",
    items:  Array< {
      __typename: "Item",
      itemId: string,
      priceCodeId: string,
      userId: string,
      commissionId: string,
      itemAcquireTypeId: string,
      categoryId: string,
      locationId: string,
      sectionId: string,
      statusId: string,
      taxTypeId: string,
      number: string,
      name: string,
      description: string,
      price: string,
      cost: string,
      modifiedBy: string,
      consignmentId: string,
      id: string,
      createdAt: string,
      updatedAt: string,
      _version: number,
      _deleted?: boolean | null,
      _lastChangedAt: number,
    } | null >,
    nextToken?: string | null,
    startedAt?: number | null,
  } | null,
};

export type OnCreateClientSubscriptionVariables = {
  filter?: ModelSubscriptionClientFilterInput | null,
};

export type OnCreateClientSubscription = {
  onCreateClient?:  {
    __typename: "Client",
    id: string,
    clientId: string,
    clientTypeId: string,
    firstName: string,
    lastName: string,
    companyName?: string | null,
    account: string,
    receiveMailInd: boolean,
    nextItemNumber: string,
    phone?: string | null,
    email?: string | null,
    createTimestamp?: string | null,
    activeTimestamp?: string | null,
    inactiveTimestamp?: string | null,
    modifiedBy: string,
    items?:  Array< {
      __typename: "Item",
      itemId: string,
      priceCodeId: string,
      userId: string,
      commissionId: string,
      itemAcquireTypeId: string,
      categoryId: string,
      locationId: string,
      sectionId: string,
      statusId: string,
      taxTypeId: string,
      number: string,
      name: string,
      description: string,
      price: string,
      cost: string,
      modifiedBy: string,
      consignmentId: string,
      id: string,
      createdAt: string,
      updatedAt: string,
      _version: number,
      _deleted?: boolean | null,
      _lastChangedAt: number,
    } | null > | null,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
  } | null,
};

export type OnUpdateClientSubscriptionVariables = {
  filter?: ModelSubscriptionClientFilterInput | null,
};

export type OnUpdateClientSubscription = {
  onUpdateClient?:  {
    __typename: "Client",
    id: string,
    clientId: string,
    clientTypeId: string,
    firstName: string,
    lastName: string,
    companyName?: string | null,
    account: string,
    receiveMailInd: boolean,
    nextItemNumber: string,
    phone?: string | null,
    email?: string | null,
    createTimestamp?: string | null,
    activeTimestamp?: string | null,
    inactiveTimestamp?: string | null,
    modifiedBy: string,
    items?:  Array< {
      __typename: "Item",
      itemId: string,
      priceCodeId: string,
      userId: string,
      commissionId: string,
      itemAcquireTypeId: string,
      categoryId: string,
      locationId: string,
      sectionId: string,
      statusId: string,
      taxTypeId: string,
      number: string,
      name: string,
      description: string,
      price: string,
      cost: string,
      modifiedBy: string,
      consignmentId: string,
      id: string,
      createdAt: string,
      updatedAt: string,
      _version: number,
      _deleted?: boolean | null,
      _lastChangedAt: number,
    } | null > | null,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
  } | null,
};

export type OnDeleteClientSubscriptionVariables = {
  filter?: ModelSubscriptionClientFilterInput | null,
};

export type OnDeleteClientSubscription = {
  onDeleteClient?:  {
    __typename: "Client",
    id: string,
    clientId: string,
    clientTypeId: string,
    firstName: string,
    lastName: string,
    companyName?: string | null,
    account: string,
    receiveMailInd: boolean,
    nextItemNumber: string,
    phone?: string | null,
    email?: string | null,
    createTimestamp?: string | null,
    activeTimestamp?: string | null,
    inactiveTimestamp?: string | null,
    modifiedBy: string,
    items?:  Array< {
      __typename: "Item",
      itemId: string,
      priceCodeId: string,
      userId: string,
      commissionId: string,
      itemAcquireTypeId: string,
      categoryId: string,
      locationId: string,
      sectionId: string,
      statusId: string,
      taxTypeId: string,
      number: string,
      name: string,
      description: string,
      price: string,
      cost: string,
      modifiedBy: string,
      consignmentId: string,
      id: string,
      createdAt: string,
      updatedAt: string,
      _version: number,
      _deleted?: boolean | null,
      _lastChangedAt: number,
    } | null > | null,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
  } | null,
};

export type OnCreateItemSubscriptionVariables = {
  filter?: ModelSubscriptionItemFilterInput | null,
};

export type OnCreateItemSubscription = {
  onCreateItem?:  {
    __typename: "Item",
    itemId: string,
    priceCodeId: string,
    userId: string,
    commissionId: string,
    itemAcquireTypeId: string,
    categoryId: string,
    locationId: string,
    sectionId: string,
    statusId: string,
    taxTypeId: string,
    number: string,
    name: string,
    description: string,
    price: string,
    cost: string,
    modifiedBy: string,
    consignmentId: string,
    id: string,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
  } | null,
};

export type OnUpdateItemSubscriptionVariables = {
  filter?: ModelSubscriptionItemFilterInput | null,
};

export type OnUpdateItemSubscription = {
  onUpdateItem?:  {
    __typename: "Item",
    itemId: string,
    priceCodeId: string,
    userId: string,
    commissionId: string,
    itemAcquireTypeId: string,
    categoryId: string,
    locationId: string,
    sectionId: string,
    statusId: string,
    taxTypeId: string,
    number: string,
    name: string,
    description: string,
    price: string,
    cost: string,
    modifiedBy: string,
    consignmentId: string,
    id: string,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
  } | null,
};

export type OnDeleteItemSubscriptionVariables = {
  filter?: ModelSubscriptionItemFilterInput | null,
};

export type OnDeleteItemSubscription = {
  onDeleteItem?:  {
    __typename: "Item",
    itemId: string,
    priceCodeId: string,
    userId: string,
    commissionId: string,
    itemAcquireTypeId: string,
    categoryId: string,
    locationId: string,
    sectionId: string,
    statusId: string,
    taxTypeId: string,
    number: string,
    name: string,
    description: string,
    price: string,
    cost: string,
    modifiedBy: string,
    consignmentId: string,
    id: string,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
  } | null,
};
